version: '3'
services:
  logic:
    build: ./Microservices/FRCM
  api_service:
    build: ./Microservices/API
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    depends_on:
      - logic