apiVersion: apps/v1
kind: Deployment
metadata:
  name: fireguard-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fireguard
  template:
    metadata:
      labels:
        app: fireguard
    spec:
      containers:
      - name: fireguard
        image: haakonm/fireguard-api  # You need to replace <your-image-path> with your Docker image path in a registry.
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
