apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logic
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
      - name: logic
        image: haakonm/fireguard-frcm  # You need to replace <your-image-path> with your Docker image path in a registry.
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MET_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: fireguard-secrets
              key: MET_CLIENT_ID
        - name: MET_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: fireguard-secrets
              key: MET_CLIENT_SECRET
        - name: FIREBASE_CREDENTIALS_BASE64
          valueFrom:
            secretKeyRef:
              name: fireguard-secrets
              key: FIREBASE_CREDENTIALS_BASE64
